use defmt::{info, trace};

use embassy_embedded_hal::{SetConfig, shared_bus::asynch::spi::SpiDeviceWithConfig};
use embassy_stm32::mode;
use embassy_stm32::spi::Spi;
use embassy_stm32::{gpio::Output, spi, time::mhz};
use embassy_sync::blocking_mutex::raw::{CriticalSectionRawMutex, RawMutex};
use embassy_time::Delay;
use embedded_fatfs::{FileSystem, FsOptions};
use embedded_io_async::Read;

use block_device_adapters::{StreamSlice, StreamSliceError};

use sdspi::SdSpi;

use block_device_adapters::BufStream;
use block_device_adapters::BufStreamError;

use embedded_hal_async::delay::DelayNs;

use mbr_nostd::{MasterBootRecord, PartitionTable};

/// Error returned from initializing the SD card device or filesystem.
#[derive(Debug)]
pub enum InitError {
    SDSPIError(embedded_fatfs::Error<BufStreamError<sdspi::Error>>),
    BufStreamError(BufStreamError<sdspi::Error>),
    StreamSliceError(embedded_fatfs::Error<StreamSliceError<BufStreamError<sdspi::Error>>>),
    SpiSD(sdspi::Error),
}

impl From<BufStreamError<sdspi::Error>> for InitError {
    fn from(value: BufStreamError<sdspi::Error>) -> Self {
        Self::BufStreamError(value)
    }
}

impl From<embedded_fatfs::Error<StreamSliceError<BufStreamError<sdspi::Error>>>> for InitError {
    fn from(value: embedded_fatfs::Error<StreamSliceError<BufStreamError<sdspi::Error>>>) -> Self {
        Self::StreamSliceError(value)
    }
}

impl From<sdspi::Error> for InitError {
    fn from(value: sdspi::Error) -> Self {
        Self::SpiSD(value)
    }
}

/// Alias type for the SPI device used to communicate with the SD card.
pub type SPIDevice<'a> = SpiDeviceWithConfig<
    'a,
    CriticalSectionRawMutex,
    Spi<'static, mode::Async, spi::mode::Master>,
    Output<'a>,
>;

/// Alias type for a BufStream wrapping the `SdSpi` driver for the SD card.
type SdBufStream<'a> = BufStream<SdSpi<SPIDevice<'a>, Delay, aligned::A4>, 512>;

/// Alias type for the SD card filesystem.
pub type SdFilesystem<'a> = FileSystem<
    StreamSlice<SdBufStream<'a>>,
    embedded_fatfs::NullTimeProvider,
    embedded_fatfs::LossyOemCpConverter,
>;

/// Alias type for errors generated by the filesystem.
pub type FilesystemError = embedded_fatfs::Error<StreamSliceError<BufStreamError<sdspi::Error>>>;

/// Alias type for files opened by the SD card filesystem.
pub type File<'a, 'b> = embedded_fatfs::File<
    'a,
    block_device_adapters::StreamSlice<
        block_device_adapters::BufStream<
            sdspi::SdSpi<SPIDevice<'b>, embassy_time::Delay, aligned::A4>,
            512,
        >,
    >,
    embedded_fatfs::NullTimeProvider,
    embedded_fatfs::LossyOemCpConverter,
>;

pub async fn new_filesystem<'a>(
    mut spi_sd: SdSpi<
        SpiDeviceWithConfig<
            'a,
            CriticalSectionRawMutex,
            Spi<'static, mode::Async, spi::mode::Master>,
            embassy_stm32::gpio::Output<'a>,
        >,
        embassy_time::Delay,
        aligned::A4,
    >,
) -> Result<SdFilesystem<'a>, InitError> {
    // Initialize the Micro SD card.
    info!("Configuring SD card...");

    // Attempt to initialize the connected SD card.
    //
    // If this fails, either there's a problem with the
    // SPI bus or timing, there is an incompatible card
    // attached, or there is no card attached.
    info!("Attempting to initialize SD card...");
    loop {
        // Attempt to initialize the card.
        //
        // TODO: This hangs indefinetly waiting for a
        //  reply on DMA if no SD card is connected!
        if spi_sd.init(true).await.is_ok() {
            info!("Initialization succeeded, increasing clock to 25Mhz..");

            // If the initialization succeeds then we can
            // increase the speed up to the SD max of 25mhz.
            //
            // TODO: check if higher speed modes are available.
            let mut config = spi::Config::default();
            config.frequency = mhz(25);
            spi_sd.spi().set_config(config);
            info!("Initialization complete!");

            break;
        }

        // TODO: at this point, should be displaying a message indicating the lack of SD card?
        info!("Failed to initialize SD card, retrying...");
        embassy_time::Delay.delay_ns(5000u32).await;
    }

    // Attempt to read the SD card size as a sanity check.
    let size = spi_sd.size().await?;
    info!("SD card storage size: {}B", size);

    // Create a buffered stream wrapping the SD card's SPI device.
    let mut buf_stream = BufStream::new(spi_sd);

    // Try to read an MBR partition table at the start of the card.
    trace!("Attempting to read MBR...");
    let mut buf = [0; 512];
    buf_stream.read(&mut buf).await?;
    let mbr = MasterBootRecord::from_bytes(&buf).unwrap();
    let mut index = 0;
    for partition in mbr.partition_table_entries() {
        trace!("MBR Partition {}:", index);
        trace!("MBR Partition Sectors {}", partition.sector_count);
        trace!(
            "MBR Partition Logical Block Address {}",
            partition.logical_block_address
        );
        index += 1;
    }

    // Read the first partition table entry from the MBR.
    let partition = mbr.partition_table_entries()[0];
    let start_offset = partition.logical_block_address as u64 * 512;
    let end_offset = start_offset + partition.sector_count as u64 * 512;

    // Make a wrapper around the BufStream that limits the start
    // and end of reads/writes to within the partition.
    let inner = StreamSlice::new(buf_stream, start_offset, end_offset)
        .await
        .unwrap();

    // Create a filesystem using the stream slice from the partition table.
    info!("Loading partition 0 as FATFS...");
    let filesystem = FileSystem::new(inner, FsOptions::new()).await?;

    // info!("Attempting to read from filesystem...");
    // let root_dir = filesystem.root_dir();
    // let mut iter = root_dir.iter();
    // while let Some(r) = iter.next().await {
    //     let e = r?;
    //     info!("found file: {}", e.short_file_name_as_bytes());
    // }

    Ok(filesystem)
}
